# Generated by Django 5.0.4 on 2024-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaveProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Product_Name", models.CharField(max_length=50)),
                ("Product_Image", models.ImageField(upload_to="image/")),
            ],
        ),
    ]
