# Generated by Django 5.0.4 on 2024-05-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webApp", "0002_saveproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveproduct",
            name="Product_Price",
            field=models.IntegerField(default=0),
        ),
    ]
