# Generated by Django 5.0.4 on 2024-05-15 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webApp", "0003_saveproduct_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saveproduct",
            name="Product_Price",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
